### ISSUE TITLE
Fit the BLSP model

### ISSUE THREAD

**Issue by liyanghenu** [ncsuSEAL/Bayesian_LSP#11] opened 2022-09-18 15:14 UTC
We are interested in the phenological information extraction method you presented. However, when we change the data of id from 1 to 3 or 5, the following message is displayed. What should we do?

Initialize model...
Estimate phenometrics...
Error in cbind(m1, c(samp[[1]][, paste0("m1", "[", i, "]")], samp[[2]][,  : 
  object 'samp' not found

**Comment by MrJGao** [comment] 2022-09-18 16:11
Thanks for your interest. Can you provide more specific information? What changes did you make? and if you can provide some reproducible code that'd be perfect.

**Comment by liyanghenu** [comment] 2022-09-19 02:41
Thank you for the response, the specific code is as follows:
library(data.table)
library(blsp)
sample_data <- fread("Z:\\R_code\\Bayesian_LSP-main\\data\\sampleData.csv") #Sample data from GEE
single_ts <- sample_data[id == 3, .(date, evi2)] # When id == 1, we can extract phenological information successfully. However, we change the value of id to 3 or 5 , an error  which we showed before occurs when executing FitBLSP model. 
single_ts <- na.omit(single_ts)
# Fit the average model
avg_fit <- FitAvgModel(
  date_vec = single_ts$date,
  vi_vec = single_ts$evi2
)
# Fit the BLSP model
results <- FitBLSP(
  date_vec = single_ts$date,
  vi_vec = single_ts$evi2,
  initValues = avg_fit,
  verbose = TRUE
)

**Comment by MrJGao** [comment] 2022-09-19 14:48
Thank you for the feedback. 

It turns out that the data must be sorted by `date` when fitting the BLSP model, but the GEE-generated data are sometimes not in order. We fixed it by manually sorting the input data in the `FitBLSP` function, now the problem should be solved. 

The fix has been updated to GitHub (commit bb8fa7f6dacaa81ea86c1b05e642a8f49b61e3ab), you should be good to go after reinstalling your local version. If you encounter any other problems, feel free to leave us another issue here. Thanks.

**Comment by MrJGao** [comment] 2022-09-19 14:54
I'll leave this open until you confirm the problem is gone.

**Comment by HENULIYANG** [comment] 2022-09-20 09:46
> I'll leave this open until you confirm the problem is gone.

With your help, we have successfully solved the above problems. Thank you again for your timely and patient guidance

**Closed as completed** 2022-09-20 15:25 UTC
Labels: bug
